apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: applications.stable.cloud.activiti.org
spec:
  group: stable.cloud.activiti.org 
  version: v1 
  scope: Namespaced 
  names:
    plural: applications 
    singular: application
    kind: Application 
    shortNames:
    - apps
  