apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: query-services.stable.cloud.activiti.org
spec:
  group: stable.cloud.activiti.org 
  version: v1 
  scope: Namespaced 
  names:
    plural: query-services
    singular: query-service
    kind: QueryService
    shortNames:
    - query
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            serviceName:
              type: string
          required:
            - serviceName