apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: runtime-bundles.stable.cloud.activiti.org
spec:
  group: stable.cloud.activiti.org 
  version: v1 
  scope: Namespaced 
  names:
    plural: runtime-bundles
    singular: runtime-bundle
    kind: RuntimeBundle 
    shortNames:
    - rb
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            serviceName:
              type: string
          required:
            - serviceName